//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long OrderID { get; set; }
        public int Quantity { get; set; }
        public long OrderProductID { get; set; }
        public Nullable<long> ProductID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
