//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public long ProductUnit { get; set; }
        public double ProductCost { get; set; }
        public Nullable<double> ProductDiscountMax { get; set; }
        public long ProductManufacturer { get; set; }
        public long ProductSuplier { get; set; }
        public long ProductCategory { get; set; }
        public double ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public long ProductID { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductCategory ProductCategory1 { get; set; }
        public virtual ProductManufacturer ProductManufacturer1 { get; set; }
        public virtual ProductSuplier ProductSuplier1 { get; set; }
        public virtual ProductUnit ProductUnit1 { get; set; }
    }
}
